sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install flake8 pylint xmltodict aiohttp async_timeout pytz
language: python
script:
- flake8 metno --max-line-length=120
- pylint metno --max-line-length=120
deploy:
  provider: pypi
  user: __token__
  password:
    secure: acPhy5cml9OSqIg+ZRBZez0lgtUlcgVKJDoYsI1hfsWV4nNVoEETgB/z68GhpB79T9LGhmjSlE1LpaE4r/7PHAc56WckbRA+ki1z3Mu/8j1Uwl+cbGiKj7k3jHerx/USDlCc0PT3U0FY5UwTOw1QfWdXd4yv++CrJzxwlxRKbFEvqinNVrvUi6Fst4Jq7sR5wKm4JA3JUgAvDd08ouoDA3mTb5bPbhcSnzjQ8nPwbTTZD8PWGHTzT8WJcHXGZQe0hg6W+DHXrQLN95ULPfMJQlVkrjX/3jamiB0zmu0cIzGa9i+8OhgzXqvZhLX+zGQIiifD4Rs/tsRpoC5z8M/nWE39v1U9FTyG5vcUBnvQjy3UeSdTk5/aMPRGk0oOlEtP/SQcftqXiFyIvp+lkfsZLPEI9IBd9WdATcG/hyAP5v6NNKXt/ivIVu5wbaO4VrSEa4YiWIPuosoQjDViuj0BmPPV/PqTfWZOkuz28FcOK+Mo61DaYPjAPvNSY191cMABL/v9KVKTHGZ5crcBWCIUPozFPGDqserQcP4xW7QoDQufoPwLr5gwrAd37zxc6O3E2LGumCNKPmGJ0m/cn1DRzJLibSIPpKoN3zUec1Epfu/pt6Q8bFbxOlErZGJC6M9ULj/M1I0ZIWNf+U9U8pKTUsaSZE6NjlhOKv0aBH1XcYU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/pyMetno
