sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install flake8 pylint xmltodict aiohttp async_timeout pytz
language: python
script:
- flake8 metno --max-line-length=120
- pylint metno --max-line-length=120
